package gr.atc.t4m.service;

import gr.atc.t4m.dto.UserDto;
import gr.atc.t4m.dto.operations.UserCreationDto;
import gr.atc.t4m.config.properties.KeycloakProperties;
import gr.atc.t4m.service.interfaces.IKeycloakAdminService;
import gr.atc.t4m.service.interfaces.IUserManagementService;
import jakarta.ws.rs.NotFoundException;
import jakarta.ws.rs.core.Response;
import lombok.extern.slf4j.Slf4j;
import org.keycloak.admin.client.Keycloak;
import org.keycloak.admin.client.resource.UserResource;
import org.keycloak.representations.idm.ClientRepresentation;
import org.keycloak.representations.idm.GroupRepresentation;
import org.keycloak.representations.idm.RoleRepresentation;
import org.keycloak.representations.idm.UserRepresentation;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.util.List;

import static gr.atc.t4m.exception.CustomExceptions.*;

@Service
@Slf4j
public class UserManagementService implements IUserManagementService {

    private final Keycloak keycloak;

    private final KeycloakProperties keycloakProperties;

    private final IKeycloakAdminService adminService;

    private final String realm;
    private final String client;

    public UserManagementService(Keycloak keycloak, KeycloakProperties keycloakProperties, IKeycloakAdminService adminService) {
        this.keycloak = keycloak;
        this.keycloakProperties = keycloakProperties;
        this.adminService = adminService;
        realm = keycloakProperties.realm();
        client = keycloakProperties.clientId();
    }

    /**
     * Handles logout of user in Async manner for better performance
     *
     * @param userId : User ID
     */
    @Async("asyncPoolTaskExecutor")
    @Override
    public void logoutUser(String userId) {
        try {
            keycloak.realm(keycloakProperties.realm())
                    .users()
                    .get(userId)
                    .logout();
        } catch (NotFoundException e) {
            log.error("User with ID: {}, not found - Error: {}", userId, e.getMessage());
        } catch (Exception e) {
            log.error("Error during logout - Error: {}", e.getMessage());
        }
    }

    @Override
    public void deleteUser(String userId) {

    }

    @Override
    public void updateUser(UserDto user) {

    }

    /**
     * Create a new User in Keycloak
     *
     * @param userData           : User Information
     * @param autogeneratedToken : Activation Token
     * @return User ID
     * @throws DataRetrievalException         : When the pilot code does not exist in Keycloak
     * @throws KeycloakException              : When a Keycloak communication error occurs
     * @throws ResourceAlreadyExistsException : When user's email already exists
     */
    @Override
    public String createUser(UserCreationDto userData, String autogeneratedToken) {

        // Ensure that user doesn't exist in Auth Server
        UserRepresentation keycloakUser = retrieveUserRepresentationByEmail(userData.email());
        if (keycloakUser != null)
            throw new ResourceAlreadyExistsException("User with given email already exists in Keycloak");

        // Check if group/pilot exists — if still required
        GroupRepresentation userPilot = adminService.retrieveGroupRepresentationByName(userData.pilotCode().trim().toUpperCase());
        if (userPilot == null) {
            throw new DataRetrievalException("Requested pilot code does not exist in Keycloak");
        }

        UserDto user = UserDto.fromUserCreationDto(userData);
        // Set the activation token and expiry
        user.setActivationToken(autogeneratedToken);
        user.setTokenFlagRaised(false);
        user.setActivationExpiry(String.valueOf(System.currentTimeMillis() + 86400000)); // 24 Hours expiration time

        // Convert UserDto to UserRepresentation
        UserRepresentation newUser = UserDto.toUserRepresentation(user, null);
        try {
            Response response = keycloak.realm(realm)
                    .users()
                    .create(newUser);

            return extractUserIdFromResponse(response);
        } catch (Exception e) {
            log.error("Error during user creation: {}", e.getMessage(), e);
            throw new KeycloakException("Error during user creation", e);
        }
    }

    /**
     * Extract UserId from Keycloak Response if successful
     *
     * @param response : Keycloak Response
     * @return UserId or Null
     */
    private String extractUserIdFromResponse(Response response) {
        // Check if the user was created successfully
        if (response.getStatus() == 201) {  // 201 Created
            // Extract user ID from Location header
            String locationHeader = response.getHeaderString("Location");
            String userId = extractUserIdFromLocation(locationHeader);
            log.info("User created successfully with ID: {}", userId);
            return userId;
        } else {
            // Handle error response
            String errorMsg = response.readEntity(String.class);
            log.error("Failed to create user in Keycloak. Status: {}, Response: {}", response.getStatus(), errorMsg);
            throw new KeycloakException("Failed to create user in Keycloak. Status: " + response.getStatus() + ", Response: " + errorMsg);
        }
    }

    /**
     * Extract user ID from Location header
     * Location format: <a href="http://keycloak-host:port/auth/admin/realms/">...</a>{realm}/users/{user-id}
     */
    private String extractUserIdFromLocation(String locationHeader) {
        if (locationHeader != null) {
            // Get the last part of the URL which is the user ID
            return locationHeader.substring(locationHeader.lastIndexOf('/') + 1);
        }
        throw new RuntimeException("User ID not found in response");
    }

    @Override
    public void updateUser(UserDto user, String userId) {
        try {
            UserResource userResource = keycloak.realm(realm)
                    .users()
                    .get(userId);

            UserRepresentation existing = userResource.toRepresentation();
            if (existing == null)
                throw new ResourceNotPresentException("User with ID: " + userId + " not found");

            userResource.update(UserDto.toUserRepresentation(user, existing));
        } catch (Exception e) {
            log.error("Error updating user {}: {}", userId, e.getMessage(), e);
            throw new KeycloakException("Error updating user with id = " + userId, e);
        }
    }

    /**
     * Retrieve all Users stored in Keycloak
     *
     * @return List<UserDto>
     */
    @Override
    public List<UserDto> retrieveAllUsers() {
        try {
            List<UserRepresentation> users = keycloak.realm(realm)
                    .users()
                    .list();

            return users.stream()
                    .map(UserDto::fromUserRepresentation)
                    .toList();
        } catch (Exception e) {
            log.error("Error retrieving all users: {}", e.getMessage(), e);
            throw new KeycloakException("Error retrieving all users", e);
        }
    }

    @Override
    public List<UserDto> retrieveUsersByPilotCode(String pilotCode) {
        return List.of();
    }


    /**
     * Retrieve User By ID
     *
     * @param userId : User ID
     * @return UserRepresentation
     * @throws ResourceNotPresentException : Thrown when a user if not found in Keycloak
     */
    @Override
    public UserDto retrieveUserById(String userId) {
        UserRepresentation user = retrieveUserRepresentationById(userId);
        if (user == null)
            throw new ResourceNotPresentException("User with ID " + userId + " not found");

        return UserDto.fromUserRepresentation(user);
    }

    /**
     * Call functions to assign roles to user
     *
     * @param newUserDetails      : User details
     * @param userId              : User ID
     */
    @Override
    @Async("asyncPoolTaskExecutor")
    public void assignRolesToUser(UserCreationDto newUserDetails, String userId) {
//            // Trigger role assignments depending on use cases (Creation or Update)
//            if (existingUserDetails == null) {
                // Assign Realm Role
//                assignRealmRole(newUserDetails.pilotRole().toUpperCase(), userId, false);
//
//                // Assign Client Role
//                assignClientRole(newUserDetails.userRole().toUpperCase(), userId, false);
        // Locate the User Representation
        UserRepresentation existingUser = retrieveUserRepresentationById(userId);
        if (existingUser == null)
            return;

        try {
            RoleRepresentation role = keycloak.realm(realm)
                    .roles()
                    .get(newUserDetails.pilotRole())
                    .toRepresentation();

            keycloak.realm(realm)
                    .users()
                    .get(userId)
                    .roles()
                    .realmLevel()
                    .add(List.of(role));



            ClientRepresentation clientRepresentation = keycloak.realm(realm)
                    .clients()
                    .findByClientId(client)
                    .getFirst();

            role =keycloak.realm(realm)
                    .clients()
                    .get(clientRepresentation.getId())
                    .roles()
                    .get(newUserDetails.userRole())
                    .toRepresentation();

            keycloak.realm(realm)
                    .users()
                    .get(userId)
                    .roles()
                    .clientLevel(clientRepresentation.getId())
                    .add(List.of(role));
        } catch (Exception e) {
            log.error("Error updating user {}: {}", userId, e.getMessage());
        }
    }


    /**
     * Function to assign Realm Role to user
     *
     * @param pilotRole : Pilot Role to be assigned to User
     * @param userId    : ID of user
     * @throws NotFoundException : When Pilot Role (Realm Role) is not Found
     */
    @Override
    public void assignRealmRole(String pilotRole, String userId) {
        try {
            RoleRepresentation role = keycloak.realm(realm)
                    .roles()
                    .get(pilotRole)
                    .toRepresentation();

            keycloak.realm(realm)
                    .users()
                    .get(userId)
                    .roles()
                    .realmLevel()
                    .add(List.of(role));
        } catch (NotFoundException e) {
            log.error("Realm role '{}' not found in Keycloak", pilotRole);
        } catch (Exception e) {
            log.error("Unable to assign realm role of {} to user {}", pilotRole, userId);
        }
    }

    @Override
    public void assignClientRole(String userRole, String userId) {
    }

    /**
     * Retrieve a User By Email
     *
     * @param email : User Email
     * @return UserRepresentation
     */
    private UserRepresentation retrieveUserRepresentationByEmail(String email) {
        try {
            List<UserRepresentation> users = keycloak.realm(realm)
                    .users()
                    .searchByEmail(email, true); // Search by Exact Match

            return users.stream()
                    .findFirst()
                    .orElse(null);
        } catch (NotFoundException e){
            return null;
        } catch (Exception e) {
            log.error("Error retrieving user by email from Keycloak: {}", e.getMessage(), e);
            throw new KeycloakException("Error retrieving user by email from Keycloak", e);
        }
    }

    /**
     * Retrieve a User By Email
     *
     * @param userId : User ID
     * @return UserRepresentation
     */
    private UserRepresentation retrieveUserRepresentationById(String userId) {
        try {
            return keycloak.realm(realm)
                    .users()
                    .get(userId)
                    .toRepresentation();
        } catch (NotFoundException e){
            return null;
        } catch (Exception e) {
            log.error("Error retrieving user from Keycloak: {}", e.getMessage(), e);
           throw new KeycloakException("Error retrieving user from Keycloak", e);
        }
    }
}
