package gr.atc.t4m.service.interfaces;

import gr.atc.t4m.dto.UserDto;
import gr.atc.t4m.dto.operations.UserCreationDto;

import java.util.List;

public interface IUserManagementService {

    void logoutUser(String userId);

    void deleteUser(String userId);

    void updateUser(UserDto user);

    String createUser(UserCreationDto newUser, String autogeneratedToken);

    void assignRolesToUser(UserCreationDto userData, String userId);

    void assignRealmRole(String userRole, String userId);

    void assignClientRole(String userRole, String userId);

    void updateUser(UserDto user, String userId);

    List<UserDto> retrieveAllUsers();

    List<UserDto> retrieveUsersByPilotCode(String pilotCode);

    UserDto retrieveUserById(String userId);
}
