package gr.atc.t4m.service.interfaces;

import gr.atc.t4m.dto.UserDto;
import gr.atc.t4m.dto.operations.PasswordsDto;
import gr.atc.t4m.dto.operations.UserCreationDto;
import org.springframework.scheduling.annotation.Async;

import java.util.List;

public interface IUserManagementService {

    void logoutUser(String userId);

    void deleteUser(String userId);

    void updateUser(UserDto user);

    String createUser(UserCreationDto newUser, String autogeneratedToken);

    void assignRolesToUser(UserDto userData);

    void assignRolesToUser(UserCreationDto newUserDetails, String userId);

    void assignRealmRole(String userRole, String userId);

    void assignClientRole(String userRole, String userId);

    List<UserDto> retrieveAllUsers();

    List<UserDto> retrieveUsersByPilotCode(String pilotCode);

    UserDto retrieveUserById(String userId);

    void changePassword(PasswordsDto passwords, String userId);

    void forgotPassword(String email);

    void resetPassword(String userId, String resetToken, String password);
}
