package gr.atc.t4m.service.interfaces;

import gr.atc.t4m.dto.UserDto;
import gr.atc.t4m.dto.UserRoleDto;
import gr.atc.t4m.dto.operations.PasswordsDto;
import gr.atc.t4m.dto.operations.UserCreationDto;
import org.keycloak.admin.client.resource.UserResource;
import org.springframework.scheduling.annotation.Async;

import java.util.List;

public interface IUserManagementService {

    void logoutUser(String userId);

    void deleteUser(String userId);

    void updateUser(UserDto user);

    String createUser(UserCreationDto newUser, String autogeneratedToken);

    void assignRolesToUser(UserDto userData);

    boolean assignRealmRole(String userRole, String userId, UserResource userResource);

    boolean assignClientRole(String userRole, String userId, UserResource userResource);

    List<UserDto> retrieveAllUsers();

    List<UserDto> retrieveUsersByPilotCode(String pilotCode);

    List<UserDto> retrieveUsersByPilotCodeAndUserRole(String pilotCode, String userRole);

    List<UserDto> retrieveAllUsersByUserRole(String jwtPilotRole, String jwtPilot, String userRole);

    UserDto retrieveUserById(String userId);

    void changePassword(PasswordsDto passwords, String userId);

    void forgotPassword(String email);

    void resetPassword(String userId, String resetToken, String password);

    void activateUser(String userId, String activationToken, String password);
}
